server:
  port: 9010
spring:
  application:
    name: LostItem
  datasource:
    url: jdbc:mysql://localhost:3306/lostitem
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver